version: "3.8"

services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - LOCALSTACK_API_KEY=
      - SERVICES=cognito-idp,iam,lambda,s3  # <- must include 'cognito'
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/var/lib/localstack"

